language: cpp
addons:
  apt:
    sources:
      - neon
      - sourceline: 'deb http://archive.neon.kde.org/user xenial main'
        key_url: 'http://archive.neon.kde.org/public.key'
    packages:
      - cmake
      - extra-cmake-modules
      - gettext
      - kio-dev
      - libatasmart-dev
      - libboost-python-dev
      - libkf5config-dev
      - libkf5coreaddons-dev
      - libkf5i18n-dev
      - libkf5iconthemes-dev
      - libkf5parts-dev
      - libkf5service-dev
      - libkf5solid-dev
      - libkpmcore-dev
      - libparted-dev
      - libpolkit-qt5-1-dev
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libyaml-cpp-dev
      - os-prober
      - pkg-config
      - python3-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qttools5-dev-tool

script:
  - cmake -DWEBVIEW_FORCE_WEBKIT=1 -DKDE_INSTALL_USE_QT_SYS_PATHS=ON .
  - make
