language: cpp
sudo: required

services:
  - docker

before_install:
  - docker build -t calamares .

script:
  - docker run -v $PWD:/build calamares bash -lc "cd /build && cmake -DWEBVIEW_FORCE_WEBKIT=1 -DKDE_INSTALL_USE_QT_SYS_PATHS=ON . && make -j2"
