name: 'Notify on Push'
description: 'Notify Matrix room'

inputs:
  room:
    description: 'Matrix Room ID'
    required: true
  token:
    description: 'Matrix Token'
    required: true
  message:
    description: 'Message to send'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -s -XPOST -d $( echo "$INPUT_MESSAGE" | jq -Rs '{"msgtype": "m.text", "body":@text}' ) "https://matrix.org/_matrix/client/r0/rooms/%21${INPUT_ROOM}/send/m.room.message?access_token=${INPUT_TOKEN}" > /dev/null
